### ISSUE TITLE
Pagina desatualizada 

### ISSUE THREAD

**Issue by castroguifetz** [everaldoscabral/Monitoramento_Sefaz#2]
Bom dia , nao está funcionando corretamente, a pagina esta incorreta 
http://www.nfe.fazenda.gov.br/portal/disponibilidade.aspx?versao=0.00&tipoConteudo=P2c98tUpxrI=

fiz um script para teste de download da pagina: 

#!/usr/bin/env bash

# Defina o URL da página de disponibilidade da Receita Federal
URL="http://www.nfe.fazenda.gov.br/portal/disponibilidade.aspx?versao=0.00&tipoConteudo=P2c98tUpxrI="

# Defina o caminho onde o conteúdo será salvo
ARQUIVO_TEMPORARIO="/tmp/statusNFE.txt"

# Verifique se o comando 'curl' está disponível no sistema
if ! command -v curl &>/dev/null; then
  echo "Erro: O comando 'curl' não está disponível. Certifique-se de que o curl esteja instalado."
  exit 1
fi

# Faça o download da página e salve o conteúdo no arquivo temporário
if curl -s -k -o "$ARQUIVO_TEMPORARIO" "$URL"; then
  echo "O conteúdo da página foi baixado com sucesso e salvo em $ARQUIVO_TEMPORARIO."
else
  echo "Erro: Falha ao baixar o conteúdo da página."
  exit 1
fi

 e ela apresentou o seguint erro :

Erro: Falha ao baixar o conteúdo da página.

**Comment by everaldoscabral** [comment]
Certeza?  A URL na macro do.host abriu normalmente. Você viu que tem um template aonde tem um host com a macro da URL?

http://www.nfe.fazenda.gov.br/portal/disponibilidade.aspx?versao=4.00&amp;tipoConteudo=Skeuqr8PQBY=

**Comment by castroguifetz** [comment]
verificado url e a mesma esta como acima , consegui fazer rodar usando o comando no shell do linux 
![image](https://github.com/everaldoscabral/Monitoramento_Sefaz/assets/124789416/96d3ce56-48d5-4cb7-8fc4-e55007648b9a)
porem no zabbix ele me retorna 0 no discovery 

![image](https://github.com/everaldoscabral/Monitoramento_Sefaz/assets/124789416/bcbf6990-12b9-40cf-94b1-f9be98fa38b7)

**Comment by castroguifetz** [comment]
consegui resolver da seguinte maneira :

alterei o zabbix_agent.conf para nao passar parametros pra executar o discovery:
UserParameter=discovery,/usr/lib/zabbix/externalscripts/sefaznfe.discovery.sh
alterei o scrip de discovery deixando ele desta maneira : 

#!/usr/bin/env bash

# Verifica se o script tem permissão de execução
if [ ! -x "$0" ]; then
  echo "2" # Código de erro 2 para permissão de execução
  exit 2
fi

# Defina o URL da página de disponibilidade da Receita Federal
URL="http://www.nfe.fazenda.gov.br/portal/disponibilidade.aspx?versao=0.00&tipoConteudo=P2c98tUpxrI="

# Defina o caminho onde o conteúdo será salvo
ARQUIVO_TEMPORARIO="/tmp/statusNFE.txt"
COOKIE_FILE="/tmp/cookies.txt"
LOG_FILE="/tmp/statusNFE.log"

# Função para registrar mensagens no arquivo de log
log() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"
}

# Verifique se o comando 'curl' está disponível no sistema
log "Verificando a disponibilidade do comando 'curl'..."
if ! command -v curl &>/dev/null; then
  log "Erro: O comando 'curl' não está disponível. Certifique-se de que o curl esteja instalado."
  echo "1" # Código de erro 1 para 'curl' não disponível
  exit 1
else
  log "Comando 'curl' disponível."
fi

# Tentativa de download da página
log "Tentando baixar o conteúdo da página da Receita Federal..."
if curl -s -k -L -c "$COOKIE_FILE" -o "$ARQUIVO_TEMPORARIO" "$URL"; then
  log "O conteúdo da página foi baixado com sucesso e salvo em $ARQUIVO_TEMPORARIO."
  echo "0" # Código de sucesso
else
  log "Erro: Falha ao baixar o conteúdo da página."
  log "Verifique os detalhes abaixo:"
  log "URL: $URL"
  log "Arquivo Temporário: $ARQUIVO_TEMPORARIO"
  log "Arquivo de Cookies: $COOKIE_FILE"
  echo "1" # Código de erro 1 para falha no download
  exit 1
fi


e por ultimo alterei o template pra nao passar parametro no discovery :
![image](https://github.com/everaldoscabral/Monitoramento_Sefaz/assets/124789416/6a19f6fc-439f-4890-9c67-a718f7640981)

apos isso ficou tudo OK 
![image](https://github.com/everaldoscabral/Monitoramento_Sefaz/assets/124789416/61f6d7e1-8b28-47b9-978d-fd37cc745b68)
